### ISSUE TITLE
Backend Linter Fixes

### ISSUE THREAD

**Issue by SpookyBeverage** [AutomatingSciencePipeline/Monorepo#122]
Time Spent
David: 6hrs

**Comment by SpookyBeverage** [comment]
Mostly straight forward, had a bit where the experiments weren't running  that was difficult to fix but restarted my computer did it

**Comment by budak7273** [comment]
+3 hours doing additional research on how to best handle exceptions.

We can still catch generic exception as long as we re-throw:

**Comment by budak7273** [comment]
Configured an auto-formatter and set it up to not reformat our long print calls 
https://stackoverflow.com/questions/71078751/vs-code-python-formatting-change-max-line-length-with-autopep8-yapf-black
https://code.visualstudio.com/docs/python/editing#_formatting
