### ISSUE TITLE
Python grpcio update broke new builds

### ISSUE THREAD

**Issue by budak7273** [AutomatingSciencePipeline/Monorepo#129]

**Comment by budak7273** [comment]
An update to grpcio caused the backend to never execute any files, forever looping this message in the log:
```
thread_pool.cc:253]                   Waiting for thread pool to idle before forking
thread_pool.cc:253]                   Waiting for thread pool to idle before forking
thread_pool.cc:253]                   Waiting for thread pool to idle before forking
```
With the google search term : `python "Waiting for thread pool to idle before forking"`

https://github.com/ray-project/ray/issues/31729
https://github.com/grpc/grpc/issues/32306
https://pypi.org/project/grpcio/1.52.0/#history

we found these. Turns out a recently released grpcio version (which was being grabbed by pip during container build because it always grabbed latest) breaks this in our project.

A bandaid fix is adding `grpcio==1.49.1` to `requirements.txt`, but we should switch over to a system that ensures that a specific version of python dependencies is installed so this can't happen again.

**Comment by gnossen** [comment]
Please note that `grpcio==1.52.0` has been yanked.

**Comment by budak7273** [comment]
@gnossen Oh, I didn't realize it would notify you when I linked the issue; hi. Thank you for handling that quickly.

Regardless, it revealed that we should have been handling our python dependencies in a cleaner manner.

**Comment by budak7273** [comment]
(#132) I set up pipenv to manage dependencies and tested it locally. Since 1.52.0 was yanked I don't need to specify a version of grpcio.

@SpookyBeverage @rrobinson281 @rhit-chanb you should delete your backend virtual environment folder and run the dev setup script again so that we're sure pipenv makes a "nice" version of it

**Comment by budak7273** [comment]
+3 hours
