### ISSUE TITLE
Convert Supabase to Firebase

### ISSUE THREAD

**Issue by SpookyBeverage** [AutomatingSciencePipeline/Monorepo#15]
Time to convert Supabase to Firebase since we are going to try firebase for the time being

Work Done Week 9:
David: 2hrs

Work Done Week 5: 
David: ~ 1hr

**Comment by SpookyBeverage** [comment]
Looked around at the config generation going to make a different branch and make it so that it's non dependent on proc_msg and so that it will create config files instead of things that need to be passed via command line

**Comment by budak7273** [comment]
Supabase is totally gone from the frontend now, backend is still hosted as part of the supabase docker compose

**Comment by budak7273** [comment]
+1 hour removing backend container from supabase, see #55
