### ISSUE TITLE
Write backend tests

### ISSUE THREAD

**Issue by rrobinson281** [AutomatingSciencePipeline/Monorepo#150]
Tests need to be written for the system and Python CI Task

**Comment by budak7273** [comment]
+1 hour working with Riley
Sent resources from SQA in the useful links channel

**Comment by rrobinson281** [comment]
3-hr Researching pytest

3-hrs Working on test fixes for backend

1-hr with @budak7273 on designing test skeleton for gen configs

**Comment by SpookyBeverage** [comment]
2 Hours with @rrobinson281 writing tests for the the parameter datatypes

**Comment by SpookyBeverage** [comment]
+3 hours working on Writing Manual Tests and started work on testing experiment data

**Comment by SpookyBeverage** [comment]
+ 2 hours, finished writing tests for Experiment Data

**Comment by SpookyBeverage** [comment]
+ 2 hours working with Riley on testConfig

**Comment by SpookyBeverage** [comment]
+ 4 Hours working on tests

**Comment by SpookyBeverage** [comment]
+ 2 hours working on tests
