### ISSUE TITLE
Experiment Trial Timeout

### ISSUE THREAD

**Issue by SpookyBeverage** [AutomatingSciencePipeline/Monorepo#159]

**Comment by SpookyBeverage** [comment]
Look into this Later me
https://docs.python.org/3/library/subprocess.html#subprocess.Popen.communicate
+ 1hr research

**Comment by budak7273** [comment]
+1hr troubleshooting

**Comment by SpookyBeverage** [comment]
+ 2 hrs

**Comment by budak7273** [comment]
+0.5 hrs PR review process
