### ISSUE TITLE
Switch to Typescript for the frontend

### ISSUE THREAD

**Issue by budak7273** [AutomatingSciencePipeline/Monorepo#17]
Pros
- Guarantee types match during runtime -> fewer runtime bugs
- Better linting, code quality, intellisense
- Better dev experience
- Next.js [supports it](https://nextjs.org/docs/basic-features/typescript)

Cons
- Typescript is not taught at Rose (but it's really close to JS)
- End result code in the browser does not directly match dev sources (we're already using Next.js -> React, so this is already happening though)
- Additional steps required to configure builds
- Setting up type imports can be troublesome

**Comment by SpookyBeverage** [comment]
Turns out to use react components you need be using a .tsx file and not .ts so after figuring out how to fix that blunder, I converted each of the files from .js to .ts or .tsx depending on if they used any components

**Comment by budak7273** [comment]
+3.5 hours reviewing PR, researching typescript best practice, turning on extra strictness settings, and dealing with the problems they caused

**Comment by budak7273** [comment]
Useful:

https://www.youtube.com/watch?v=AEQij4AnjYU

https://rapidapi.com/guides/next-api-error-handling
