### ISSUE TITLE
Final Version of the Poster

### ISSUE THREAD

**Issue by SpookyBeverage** [AutomatingSciencePipeline/Monorepo#180]

**Comment by budak7273** [comment]
+2 hours earlier in the week as a group

**Comment by budak7273** [comment]
+0.5 hours finalizing

**Comment by SpookyBeverage** [comment]
Perhaps a system diagram (in addition to our user flow?)

Perhaps explanations of what we use the tech for?

The final poster cutoff is 6th week (or the print shop might not do it in time)

More posters to compare with: https://photos.app.goo.gl/5nG6YUxRDddj6gfWA

**Comment by SpookyBeverage** [comment]
Perhaps a system diagram (in addition to our user flow?)

Perhaps explanations of what we use the tech for?

The final poster cutoff is 6th week (or the print shop might not do it in time)

More posters to compare with: https://photos.app.goo.gl/5nG6YUxRDddj6gfWA

**Comment by SpookyBeverage** [comment]
Perhaps a system diagram (in addition to our user flow?)

Perhaps explanations of what we use the tech for?

The final poster cutoff is 6th week (or the print shop might not do it in time)

More posters to compare with: https://photos.app.goo.gl/5nG6YUxRDddj6gfWA

**Comment by budak7273** [comment]
+2 hours finalizing and making formatting consistent
