### ISSUE TITLE
Update Project Proposal For Next Year

### ISSUE THREAD

**Issue by SpookyBeverage** [AutomatingSciencePipeline/Monorepo#181]
Ours: https://docs.google.com/document/d/1vJ8NWwbMJJZjZgpqT94HyOrul3Lrsjtp8M8bnVIdeXk/edit

Other Group: https://docs.google.com/document/d/1K0RmqMpwZmyACK2Snnon3JDl0cTJJB9MH0QC80YTT1o/edit

**Comment by rhit-chanb** [comment]
riley and brian - 2hrs
