### ISSUE TITLE
Add a Help Button on Dashboard - 5/3

### ISSUE THREAD

**Issue by budak7273** [AutomatingSciencePipeline/Monorepo#185]

**Comment by budak7273** [comment]
This one should be pretty straightforward. Locate the file that controls the main page (with the login boxes) and add a link to our Github Wiki page. Copy an existing link-type element from somewhere else on the page/site to get the formatting correct.

**Comment by budak7273** [comment]
NextJS might have some sort of link security feature (sometimes it does for images), but if you encounter that, just google how to solve it

**Comment by rhit-windsors** [comment]
This will include writing the guide for running the experiment.
