### ISSUE TITLE
Update package dependencies

### ISSUE THREAD

**Issue by rhit-chanb** [AutomatingSciencePipeline/Monorepo#19]
In the frontend, namely, mantine has a new version number that has a couple breaking changes but also might help fix issue at https://github.com/AutomatingSciencePipeline/Monorepo/issues/7#issuecomment-1258931857

**Comment by budak7273** [comment]
Jason gave us the okay to work on this, citing that many past projects have failed due to their dependencies not being updated over time, and then no one being able to update them across the large version gap

**Comment by rhit-chanb** [comment]
Updated Heroicons to v2, removed unused dependencies (3 hrs)

**Comment by rhit-chanb** [comment]
Updated the rest of the packages and wrote a document detailing the process for doing so (6 hrs)

**Comment by budak7273** [comment]
Mantine is the only dependency left, it would require a bigger rewrite to update
