### ISSUE TITLE
'Delete experiment' functionality

### ISSUE THREAD

**Issue by budak7273** [AutomatingSciencePipeline/Monorepo#205]
Clean up database files related to an experiment after it is no longer needed

**Comment by SpookyBeverage** [comment]
David's Guide

1. Go to `ExperimentListing.tsx` in the components directory in the frontend
2. Add a new button with a onClick that deletes the information about the experiment from Firebase and MongoDB
3.

**Comment by sugiyat** [comment]
+1 hour Created a button and added test functionality

**Comment by sugiyat** [comment]
+3 hour compile bug

**Comment by sugiyat** [comment]
Wed
+1.5 hour compile bug w/ Rob
+1.5 hour researching frontend/backend endpoints

Fri
+1 hour developing experiment delete endpoint for frontend
+0.5 hour developing experiment delete endpoint for backend
+1.5 hour changing structure to connect to firebase directly from frontend

**Comment by sugiyat** [comment]
Potential TODO: Add confirmation button to delete button
