### ISSUE TITLE
Frontend: Timestamp of expected finish time

### ISSUE THREAD

**Issue by budak7273** [AutomatingSciencePipeline/Monorepo#206]

**Comment by SpookyBeverage** [comment]
David's Tips

The area where this will be implemented will be in `ExperimentListing` Component in `ExperimentListing.tsx`, You just have to add a new timestamp for expected finish type and use the expected experiment length from the firebase object

**Comment by sugiyat** [comment]
Potential TODO: Change fraction of minutes to seconds
