### ISSUE TITLE
Example C Project from a Student

### ISSUE THREAD

**Issue by budak7273** [AutomatingSciencePipeline/Monorepo#208]
From Jason:

FYI - a current student with an executable C program can be found here:
https://github.com/osiris-zyt/CGPBrain/tree/master

It is not currently coded to allow for a configuration file to be passed, but you can at least see an example of a third language and required execution environment

**Comment by budak7273** [comment]
This is a good experiment for testing if the system can run without hyperparameter specificaitons

**Comment by budak7273** [comment]
@SpookyBeverage can work with the new team to implement this and help if they get stuck

**Comment by SpookyBeverage** [comment]
David's Fun Guide to adding more File Support

1. Figure out the magic type of the new file (i.e. a python's file's magic type is `Python script`)
2. Add a new `ExperimentType` type in the enum
3. Add handling for the new Experiment in `determine_experiment_file_type` in `app.py`
4. Figure out what command to run in `run_trial`  in `runner.py` to run a file of the desired type
5. Should be good now (Don't forget to test)

**Comment by rhit-zhangam** [comment]
On branch `c-example`, created minimal addnums example experiment, compiled via gcc in wsl. I noted the magic type as `ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=c1197072f408896cfc4845dbbe5445ef8ae70e0d, for GNU/Linux 3.2.0, not stripped`. Results are similar for the project Rob provided, just a different build id. There seems to be a difference compiling for linux vs windows, looking into it. I'm thinking I'll need to check which one the backend can execute.

Work time: ~5 hours so far

**Comment by rhit-zhangam** [comment]
Compiled via Visual Studio 2019, magic type is `PE32 executable (console) Intel 80386, for MS Windows`

**Comment by rhit-zhangam** [comment]
the mime type was `application/x-sharedlib`, using gcc with the `-no-pie` flag to compile again gave a `application/x-executable` mime type. `DispatchStep.tsx` is still rejecting it though, not sure why.

**Comment by rhit-zhangam** [comment]
ok so apparently the [dropzone](https://github.com/react-dropzone/react-dropzone/issues/1273) uses [these mime types](https://www.iana.org/assignments/media-types/media-types.xhtml) to check.
these mime types are not in the list, so that's probably why it is saying Unknown. this is probably tied to why python experiments can't be run on some setups, see #238 .

**Comment by rhit-zhangam** [comment]
backend has permission errors, I think due to the docker volume being mounted for `ExperimentFiles/`.  Work time since last work time update: ~3.5 hrs

**Comment by rhit-zhangam** [comment]
Closed with #242
