### ISSUE TITLE
Remove duplicated backend from the frontend

### ISSUE THREAD

**Issue by budak7273** [AutomatingSciencePipeline/Monorepo#22]
Apparently they copied `app.py` to `/apps/frontend/lib/backend` at some point.

I think @SpookyBeverage already looked at this and we don't need it, but now it's a card to be sure.

**Comment by SpookyBeverage** [comment]
Looking at the replicated app.py it just seems to be for testing the frontend when they were separated so I think it would be safe to delete it. and if we need it later we can just time travel

**Comment by budak7273** [comment]
Removed it in #35
