### ISSUE TITLE
Engineering Standards Assignment 10/21/22

### ISSUE THREAD

**Issue by budak7273** [AutomatingSciencePipeline/Monorepo#25]
> 1.	I posted the Engineering Standards Assignment on Moodle. There are two parts: 1) Individual part where you do a tutorial and take a quiz, and 2) Team part where you review the Software Engineering Standards in the library and any industry-specific standards for applicability to your project. This is due Week 7, Oct. 21st.

**Comment by SpookyBeverage** [comment]
Gonna track my time for this here: 30mins so far
