### ISSUE TITLE
Convert auth to use firebase auth

### ISSUE THREAD

**Issue by SpookyBeverage** [AutomatingSciencePipeline/Monorepo#28]
If we want to fully axe supabase we'll need to remove the supabase auth, This should be fine since firebase also offers authorization ability. I think any supabase auth is used in `supabase/auth`, `Components/Dashboard`, `Components/ProtectedRoute`, `pages/auth`, and `pages/index` all in the frontend folder obviously 

Here's a link to getting started with Firebase Auth: [https://firebase.google.com/docs/auth/web/start](https://firebase.google.com/docs/auth/web/start)

**Comment by rrobinson281** [comment]
+7 hours researching and converting to supabase auth

**Comment by budak7273** [comment]
+2 hours pair programming @budak7273 and @rrobinson281

**Comment by budak7273** [comment]
+2.5 hours

Used docs:
https://reactjs.org/docs/hooks-reference.html#useMemo
https://firebase.google.com/docs/reference/js/auth.usercredential.md#usercredentialuser
https://firebase.google.com/docs/auth/web/start#web-version-9_2

The Firebase docs seem to link to some old v8 content from the v9 examples, reported the problem but we have to be way of this

Additional future debugging help:
https://discord.com/channels/1017208818989539368/1017210021970460753/1035274784868671558
![Image](https://user-images.githubusercontent.com/25965766/198502722-740f9b3e-3db3-49e9-b524-c1693232be5b.png)

**Comment by budak7273** [comment]
+1 hour stupid merge conflict, I forgot to update Riley's branch from master before we did our work on it...

**Comment by budak7273** [comment]
+2 hours fixing and testing the experiment upload logic
