### ISSUE TITLE
Stripe 2 Evidence

### ISSUE THREAD

**Issue by SpookyBeverage** [AutomatingSciencePipeline/Monorepo#32]
Stripe 2 will cover the work done since the last stripe for each of the five categories.

Please submit a document that describes the teams efforts for this stripe only on the following items with general expectations of the type of material expected.  For each of the items below, include a  paragraph describing what has been accomplished by the team and pointers to actual documents would be ideal.  Also include for each section how you've addressed any of the specific feedback from Stripe 1.

1. Develop a software project plan to estimate tasks, schedule_ them with specific commitments, and Manage to the plan.
At this point, you should have an operational plan that the team is using to direct your work and assignments including an active gathering of estimates and actuals, likely using a tool like Trello or Jira.

2. Establish and refine the software requirements for the product by effective communication with stakeholders and clear specifications to define the product.
You should have confirmed the basic, starting requirements with the customer and have an overall backlog of features that will be developed. 

3. Produce a software design that accommodates architecturally significant requirements and articulates software program design at a level appropriate for the team members to implement the system.
This will vary for projects.  At this point, you should be developing more detailed design of some kind (DB, GUI, class/sequence/other UML, etc.)  

4. Implement code that solves customer problems and shows good command of software development techniques 
All projects should have defined procedures and a definition of the development practices you would use.  You should have assembled the basic tools and be developing prototypes/initial features/good understanding of existing code.  

5. Validate and verify the requirements, design, and code to the extent that is relevant to a client’s needs.
You should have an established overall plan for how the system will be validated and verified and be operating to the plan as appropriate.

**Comment by budak7273** [comment]
We covered this in Wednesday's group meeting.

+5 hours all members
