### ISSUE TITLE
Kubernetes Research

### ISSUE THREAD

**Issue by SpookyBeverage** [AutomatingSciencePipeline/Monorepo#48]
Honestly everyone should probably do this,

Links:
Start Here: https://kubernetes.io/docs/tutorials/kubernetes-basics/
https://kubernetes.io/docs/tutorials/hello-minikube/
https://devopscube.com/kubernetes-minikube-tutorial/

**Comment by rhit-chanb** [comment]
We might want to get a demo "manually" spinning up docker containers with python's os.system() function just so we can get a Dockerfile set up for the runner nodes. 
https://kubernetes.io/blog/2019/07/23/get-started-with-kubernetes-using-python/ <- old(ish) tutorial, referring to everything up to the kubernetes section. Their example uses a simple Flask webapp as the python file to run, so we should see if it works with a console app too.

**Comment by budak7273** [comment]
More research on the viability of kubernetes. Looks like the potential issue of docker swarm not working with mixed windows+linux hosts should not apply to kubernetes, but not confident. Looks like we won't need any of its load balancing capabilities.

- 22mins https://www.simplilearn.com/tutorials/kubernetes-tutorial/
- 44mins https://www.youtube.com/playlist?list=PLHq1uqvAteVvUEdqaBeMK2awVThNujwMd
  - Especially useful video (making a small python web server and deploying it with kubernetes) https://www.youtube.com/watch?v=d1ZMnV4yM1U
