### ISSUE TITLE
Get Supabase working

### ISSUE THREAD

**Issue by rhit-chanb** [AutomatingSciencePipeline/Monorepo#6]
Supabase Auth/Keys are invalid, refresh them and fix up odds and ends.

**Comment by rhit-chanb** [comment]
Tried migrating database, didn't have permissions to access existing supabase project's database, Elijah unable to access the keys to modify existing supabase project's permissions, shelving this issue for now

**Comment by budak7273** [comment]
We are sticking with our non-supabase approach for now
