### ISSUE TITLE
Fall "All the project documents (to pass on)" submission

### ISSUE THREAD

**Issue by budak7273** [AutomatingSciencePipeline/Monorepo#63]
- Don't need to include meeting notes as document; a link to the folder is fine
- Project plan and such submitted as a pdf document
- Github docs can be linked as well
- "what happened to the project this quarter" architecture diagram, demos

**Comment by SpookyBeverage** [comment]
Spent 30 Mins

**Comment by budak7273** [comment]
+30 minutes
