### ISSUE TITLE
Investigate alternatives to Supabase

### ISSUE THREAD

**Issue by SpookyBeverage** [AutomatingSciencePipeline/Monorepo#7]
We hate supabase We're going to start looking at alternatives to superbase

So far I've done ~12 hrs of work

Firebase Project: [https://console.firebase.google.com/u/0/project/gladosbase/overview](https://console.firebase.google.com/u/0/project/gladosbase/overview)

Dependencies:
- Backend: `pip install firebase-admin`
- Frontend `npm install firebase@9.10.0 --save`

Firestore Python Docs: [https://firebase.google.com/docs/firestore/quickstart](https://firebase.google.com/docs/firestore/quickstart)
Google Cloud Storage Docs: [https://cloud.google.com/storage/docs/introduction](https://cloud.google.com/storage/docs/introduction)
Cloud storage docs for frontend: [https://firebase.google.com/docs/storage/web/start#web-version-9](https://firebase.google.com/docs/storage/web/start#web-version-9)

**Comment by SpookyBeverage** [comment]
Started work on feeling out  how python and Firebase interact, Got firestore to be able upload and update collections and got file upload/download working through google cloud storage. Links to docs down below,
Only one new dependency `pip install firebase-admin` 

Firestore Python Docs: [https://firebase.google.com/docs/firestore/quickstart](https://firebase.google.com/docs/firestore/quickstart)
Google Cloud Storage Docs: [https://cloud.google.com/storage/docs/introduction](https://cloud.google.com/storage/docs/introduction)

**Comment by SpookyBeverage** [comment]
Ran into some problems with getting firebase to work on the frontend, Talked with Rob because he knows more about node stuff and we figured out that firebase-admin can't run on the frontend part, but regular firebase does (they're separate for some reason) going to get a basic back and forth between the frontend and the backend working tomorrow or maybe later when I don't have a PLC exam

New dependency added for the frontend : `npm install firebase@9.10.0 --save` docs are the same as above

**Comment by SpookyBeverage** [comment]
Looked into the cloud storage docs so I can upload files from the frontend, @google-cloud/storage doesn't work on the front end yay! Did some research and the google cloud stuff is in firebase for some reason

Cloud storage docs for frontend: [https://firebase.google.com/docs/storage/web/start#web-version-9](https://firebase.google.com/docs/storage/web/start#web-version-9)

**Comment by SpookyBeverage** [comment]
Started work on getting information from the frontend to the backend, I have something that theoretically works but a form's onsubmit lambda isn't firing for some reason causing it to not work so that's fun, wasted like 1 hour trying to fix it but I don't know enough about react/next to know what's really wrong

**Comment by SpookyBeverage** [comment]
Kind of fixed it, It was an issue with unique keys in NewExp and parameter but it somehow broke being able to tab between the fields and now you can't type more than one character in the parameters so maybe it's not fixed

**Comment by budak7273** [comment]
~45 minutes with David and Brian figuring out why the chosen Firebase packages weren't working for [this](https://github.com/AutomatingSciencePipeline/Monorepo/issues/7#issuecomment-1257434388) comment item and locating the correct packages to use instead

**Comment by budak7273** [comment]
Docs used:
- https://stackoverflow.com/questions/57161839/module-not-found-error-cant-resolve-fs-in
- https://nextjs.org/docs/messages/module-not-found
- 🌟 https://stackoverflow.com/questions/71106759/next-js-middleware-module-not-found-cant-resolve-fs
- https://github.com/vercel/next.js/issues/36237

**Comment by SpookyBeverage** [comment]
Thought of a workaround for the onSubmit and moving all information uploading to the dispatch level, added the form and user to the `DispatchStep` object and then called what would normally be called onSubmit and put what was called in the dispatch step in the .then of the function seems to be working for now, it's able to get the hyperparams to firebase and successfully sends the id of the experiment to the backend which is positive, Tomorrow or the day after I will start working on fully integrating the backend with firebase

**Comment by SpookyBeverage** [comment]
Started work on converting the backend to Firebase. Ran into some issues with making sure everything came down from Firestore but it should be fixed up now. So far when the backend gets a post request to experiments it'll pull the experiment data from Firebase and then download the experiment file to `app/ExperimentFiles` in the `services/supabase` (should probably change that but I don't want to break everything)
