### ISSUE TITLE
Stripe 1 paperwork

### ISSUE THREAD

**Issue by SpookyBeverage** [AutomatingSciencePipeline/Monorepo#8]
Stripe due Friday of next week
- Paragraph summary for each of the topic pointing to actual documents and artifacts

Project work documentation
- Requirements
- Success metrics
- Risk analysis
- Project team structure (roles)
- Collection of the “links” for Tracy to have easy access to
- There’s an example on the moodle page of what sections need to be there, but it doesn’t have to follow that format

**Comment by SpookyBeverage** [comment]
Should probably get on this soon

**Comment by budak7273** [comment]
+3 hours on 9/29 to finalize it into Project Plan Draft and Stripe 1 Doc, submitted on Moodle
