### ISSUE TITLE
Ability to clone an experiment from past runs

### ISSUE THREAD

**Issue by budak7273** [AutomatingSciencePipeline/Monorepo#83]
Gathered from the 11/30/2022 user presentation

- Re-using entered data from past experiment runs
- Frontend button to clone experiment descriptors
- Switch to generating the "parameter widgets" from the JSON definition we use for experiment hyperparameters (so you can modify the parameters you used last time in the experiment inside the copy)

**Comment by SpookyBeverage** [comment]
David Time: 2hrs

Spent Time researching how exactly new experiments are created I think I have a good grasp of how information is passed to the page and I'm gonna work trying to prefill the form
